server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  cache:
    redis:
      time-to-live: 1m
  data:
    redis:
      host: localhost
      port: 6379